name: Lanzamiento
on:
  push:
    tags:
      - 'v*'

jobs:
  lanzamiento:
    name: Lanzamiento de la nueva versión
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    
    - name: Activando el repositorio
      uses: actions/checkout@v2

    - name: Crear el lanzamiento
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Lanzamiento ${{ github.ref }}
        draft: true
        prerelease: false
  
  construccion:
    name: Construcción del paquete
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: go build -v ./...

    - name: Ubicando paquetes
      id: ubicacion
      run: |
        echo "::set-output name=fichero::$(find ./... -name katy -mindepth 1)"
    
    - name: Subir los extra
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.lanzamiento.outputs.upload_url }} 
        asset_path: ${{ steps.ubicacion.outputs.fichero }}
