name: Lanzamiento
on:
  push:
    tags:
      - 'v*'

jobs:
  lanzamiento:
    name: Lanzamiento de la nueva versión
    
    runs-on: ubuntu-latest
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
    - name: Activando el repositorio
      uses: actions/checkout@v2

    - name: Crear el lanzamiento
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Lanzamiento ${{ github.ref }}
        draft: true
        prerelease: false
  
  construccion:
    name: Construcción del paquete
    
    runs-on: ubuntu-latest
    
    needs: lanzamiento
    
    steps:
    - name: Activando el repositorio
      uses: actions/checkout@v3

    - name: Configurando Go 
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Corriendo test
      run: go test -v 
    
    - name: Construyendo la aplicacion
      run: go build -v  

    - name: Ubicando paquetes
      id: ubicacion
      run: |
        echo "::set-output name=fichero::$(find $PWD -name katy -mindepth 1)"
    
    - name: Empaquetando
      run: |
        tar -czvf katy-${GITHUB_REF#refs/*/}.tgz $(basename $(find $PWD -name katy))

    - name: Nombre del fichero
      id: nombre_fichero
      run: |
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
    - name: Ver nombre del fichero
      run: | 
        echo ${{ steps.nombre_fichero.outputs.tag }}
        echo ${{ github.ref }}
        echo ${ GITHUB_REF##*/ }
        echo ${ GITHUB.REF##*/ }
        echo ${{ github.repository }}
        echo ${ GITHUB.REPOSITORY##*/ }
    - name: Subir los extra
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.lanzamiento.outputs.upload_url }} 
        asset_path: ./katy-${{ steps.nombre_fichero.outputs.tag }}.tgz
        asset_name: katy-${{ steps.nombre_fichero.outputs.tag }}.tgz
        asset_content_type: application/gzip
